### ISSUE TITLE
x axis off

### ISSUE THREAD

**Issue by chucks1967** [ChadDevOps/Marlin-Ender-3-Max#3]
Loaded the latest firmware on ender 3 max with CR touch, did auto home, started a print and noticed that the x axis is not center. it is right a certain amount of mm towards 0 y axis is right on.

**Comment by ChadDevOps** [comment]
Strange, not seeing that, however, my printer is far from stock now. You can try changing the print bed position with `M206`. https://marlinfw.org/docs/gcode/M206.html This can be added into you pre-start machine settings in cura, or ran from octoprint/etc. You'll probably need to issue an `M500` to save the settings so they persist after a reboot.

Example: Shift the print area 10mm to the left `M206 X10`

**Comment by ChadDevOps** [comment]
Also, another option, you can get nightly builds based on the official Marlin GitHub from https://marlin.crc.id.au/. This should be closer to stock than my custom build. I tinker quite a bit with settings. They ask for a small donation to become a member for a year. There have been a LOT of updates over the past 11 months since I [originally committed the Ender 3 Max config](https://github.com/MarlinFirmware/Configurations/pull/442).
